# Generated by Django 2.0.6 on 2018-10-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stars', models.IntegerField(default=0)),
                ('release_Date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
